Task 7-4
CezaryJanicki/Cezary-Janicki-kodilla-java pull request #11
Opened 2020-09-01 20:07 UTC by CezaryJanicki

2020-09-04 16:24 UTC, marszelun requested changes

2020-09-04 16:24 UTC, marszelun commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +    public List<Country> getContinent() {
Lepsza byłaby nazwa `getCountries` (analogicznie nazwa pola: `countries`). Nie nazywaj pola tak, jak klasa, do której to pole należy.

2020-09-04 16:24 UTC, marszelun commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Country.java
> +    BigDecimal getPeopleQuantity() {
Czemu ten getter nie jest `public`?

2020-09-04 16:24 UTC, marszelun commented on kodilla-stream/src/main/java/com/kodilla/stream/world/World.java
> +    private final List<Continent> world = new ArrayList<>();
Tutaj podobna uwaga - lepiej nazwać to pole `continents`.

2020-09-04 16:24 UTC, marszelun commented on kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java
> +        Assert.assertEquals(new BigDecimal("3958902000"), result);
Test  jak najbardziej poprawny, ale długi - 2-3 kontynenty z maks. 2-3 państwami w jednym z nich byłyby wystarczające.

2020-09-04 16:24 UTC, marszelun commented on kodilla-stream/src/main/java/com/kodilla/stream/world/World.java
> +                .reduce(BigDecimal.ZERO, (sum, current) -> sum = sum.add(current));
Przypisanie `sum =` nie jest potrzebne. Ono zmienia argument lambdy, czyli nie ma żadnego znaczenia. Kod działa poprawnie dlatego, że wyrażenie `x = y` ma wartość `y`.
Ergo - wystarczy `(sum, current) -> sum.add(current)`. Liczy się wartość zwracana z lambdy, a nie przypisanie.
Jeszcze ładniej napiszesz to w postaci referencji `BigDecimal::add`.

2020-09-04 22:31 UTC, CezaryJanicki commented on kodilla-stream/src/main/java/com/kodilla/stream/world/World.java
> +                .reduce(BigDecimal.ZERO, (sum, current) -> sum = sum.add(current));
Referencja jest bardzo ladna. Zrobione.

2020-09-05 13:30 UTC, marszelun approved these changes

2020-09-05 18:49 UTC, merged