task-13-1
CezaryJanicki/Cezary-Janicki-kodilla-java pull request #15
Opened 2020-09-09 22:35 UTC by CezaryJanicki

2020-09-10 05:17 UTC, marszelun requested changes

2020-09-10 05:17 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/MovieStore.java
> +                .map(list -> list.toString())
Nie rozumiem idei tego map-a. Do czego on ma służyć?

2020-09-14 18:47 UTC, CezaryJanicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/MovieStore.java
> +                .map(list -> list.toString())
W pewnym momencie metoda println wyświetlała adresy pamięci a nie tekst, i dlatego wrzucilem toString(), ale bez tego tez dziala. Poprawilem.

2020-09-15 21:46 UTC, marszelun approved these changes

2020-10-13 11:12 UTC, merged