task 13.2
CezaryJanicki/Cezary-Janicki-kodilla-java pull request #17
Opened 2020-10-16 13:51 UTC by CezaryJanicki

2020-10-16 16:20 UTC, marszelun requested changes

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/Application.java
> +        //OrderDto orderDto = new OrderDto();
komentarz - linia do usunięcia

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderDto.java
> +    public User user;
Dlaczego te pola są publiczne?
Najlepiej domyślnie stosować `private final`. Inne opcje tylko w przypadku wyraźnej potrzeby. Tutaj takowej nie ma.

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderDto.java
> +    public boolean isRented;
Hmm... `isRented`? To miał być sklep, nie zajmuje się raczej wypożyczaniem towaru :)

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +    private InformationService informationService;
Tu znów brakuje `final`.

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +    public OrderProcessor(final InformationService informationService,
Dla odmiany `final` w tym miejscu jest raczej zbędne (nie jest oczywiście błędem).

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +            return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), false);
Zauważ, że tworzenie obiektu `OrderDto` możesz wyciągnać poniżej if...else, jako ostatni argument używając `isOrdered`.

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/Product.java
> +    String product;
Wydaje mi się, że kiedyś już to omawialiśmy - mało sensowne jest nazywanie pola tak samo, jak klasa w której się znajduje. Tutaj zapewne chodziło Ci o nazwę produktu, więc lepiej użyć `productName`, a jeszcze lepiej - krócej - po prostu `name`.
Chyba, że to jakiś kod, identyfikator itp. - wtedy też konkretniejsza nazwa (np. `code`, `ean`, `id` itp.)

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/Product.java
> +    String product;
+ pole jest `package private`, czemu nie `private final`?

2020-10-16 16:20 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/User.java
> +    String name;
pola są `package private`, czemu nie `private final`?

2020-10-16 20:02 UTC, CezaryJanicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +            return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), false);
Nie rozumiem troche jak?
if(isOrdered) {
            informationService.inform(orderRequest.getUser());
            orderRepository.createOrder(orderRequest.getUser(), orderRequest.getProduct(), orderRequest.getOrderTime());
        } else {
            return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), false);
        }
        return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), true);

2020-10-17 13:04 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +            return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), false);
```
if(isOrdered) {
informationService.inform(orderRequest.getUser());
orderRepository.createOrder(orderRequest.getUser(), orderRequest.getProduct(), orderRequest.getOrderTime());
}
return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), isOrdered);
```

2020-10-20 20:39 UTC, marszelun requested changes

2020-10-20 20:39 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderRequest.java
> +    private User user;
`final`

2020-10-20 20:39 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/OrderProcessor.java
> +        } return new OrderDto(orderRequest.getUser(), orderRequest.getProduct(), isOrdered);
Powinno być w nowej linii.

2020-10-20 20:39 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/allegro/InformationService.java
> +public class InformationService {
Tutaj przydał by się ogólny interfejs (`InformationService`) i konkretna klasa implementująca (np. `MailService`).

2020-10-25 08:35 UTC, marszelun approved these changes

2020-10-27 22:41 UTC, merged