task-14-1 for code review
CezaryJanicki/Cezary-Janicki-kodilla-java pull request #22
Opened 2020-10-22 23:06 UTC by CezaryJanicki

2020-10-23 16:57 UTC, marszelun requested changes

2020-10-23 16:57 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/forum/ForumUser.java
> +    String username = "John Smith";
`private final`. Poza tym, zgodnie z treścią zadania, pole miało być inicjowane w konstruktorze.

2020-10-23 17:38 UTC, CezaryJanicki commented on kodilla-spring/src/main/java/com/kodilla/spring/forum/ForumUser.java
> +    String username = "John Smith";
Wrzucone.

2020-11-03 21:47 UTC, marszelun approved these changes

2020-12-04 21:42 UTC, merged